name: Deployment - Test
on:
  push:
    branches:
      - deployment-test
  pull_request:
    branches:
      - deployment-test

env:
  MTURK_NAME: my_mturk_user_sandbox
  MTURK_TYPE: mturk_sandbox
  USER_EMAIL: jaythaiduong.huynh@uq.edu.au
  USER_NAME: jaythaiduong.huynh
  REPO_DIR: ~/${{ github.event.repository.name }}-${{ github.ref_name }}
  APP_NAME: ${{ github.event.repository.name }}-${{ github.ref_name }}
  APP_ENV: test
  AWS_REGION: ap-southeast-2
  SVLD_VERSION: main
  PREVIEW_URL_PREFIX: '%Mock task launched.* for preview%'
  CONT_PORT: 3000
  VPC_ID: 'vpc-02e937c4efdd7541b'
  DOMAIN: 'aufederal2022.com'

jobs:
  build-container:
    name: build-container
    runs-on: ubuntu-latest
    steps:
      - name: Authorize AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Get secrets from SSM Parameter Store
        uses: d-lab/aws-ssm-getparameters-action@main
        with:
            parameterPairs: "VPC_ID=VPC_ID,DOMAIN=DOMAIN,ECR_IMAGE_REPO=ECR_IMAGE_REPO,ACCOUNT_ID=AWS_ACCOUNT_ID,MTURK_ACCESS_KEY_ID=MTURK_ACCESS_KEY_ID,MTURK_SECRET_ACCESS_KEY=MTURK_SECRET_ACCESS_KEY,PROLIFIC_API_KEY=PROLIFIC_API_KEY,DOTNETRC=DOTNETRC,HEROKU_API_KEY=HEROKU_API_KEY,PRIVATE_KEY=PRIVATE_KEY"
            withDecryption: "true" # defaults to true

      - name: Checkout current branch
        uses: actions/checkout@v4

      - name: Build and publish image into ECR, then start the service
        uses: d-lab/serverless-mephisto@main